# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e7fdb83cb217eef5be52fa8e6042dce03dae1cb246b6e83d38ebeeedbfb5bc78cbf786eeeb08803dfdcaebcef1f152b6f41f2895cb27f67abeb87d10c6bc112

test:
  secret_key_base: 491e7cc13eaf0ad7b192b04ddca402f9460e94c0cb8a11d74aac442dab43cd8de3b624b532e682c3eee8cc783eabd7285985a5e033641a7635c155300567fae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
